title: Heston Snodgrass
author: hsnodgrass
email: hsnodgrass3@gmail.com
description: >
  Personal site for Heston Snodgrass. I enjoy coding, systems
  administration, the DevOps, site reliability, information
  security, and some normal stuff too.
baseurl: "/"
url: "https://hsnodgrass.github.io"
github_username: hsnodgrass
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: thelehhman/texture
permalink: /posts/:title/
texture:
  title: Heston Snodgrass
  tagline: Coder, SysAd, DevOps, and some InfoSec
  date_format: "%b %-d, %Y"
  social_links:
    github: hsnodgrass
    linkedin: in/hsnodgrass
  style:
    - black
  showPicker: false
  showNav: false

